defmodule Exemvi.QR.MP.Object do

  defstruct [
    :id,
    :value,
    :objects
  ]

  @root_id_atoms %{
    "00" => :payload_format_indicator,
    "01" => :point_of_initiation_method,
    "02" => :merchant_account_information,
    "03" => :merchant_account_information,
    "04" => :merchant_account_information,
    "05" => :merchant_account_information,
    "06" => :merchant_account_information,
    "07" => :merchant_account_information,
    "08" => :merchant_account_information,
    "09" => :merchant_account_information,
    "10" => :merchant_account_information,
    "11" => :merchant_account_information,
    "12" => :merchant_account_information,
    "13" => :merchant_account_information,
    "14" => :merchant_account_information,
    "15" => :merchant_account_information,
    "16" => :merchant_account_information,
    "17" => :merchant_account_information,
    "18" => :merchant_account_information,
    "19" => :merchant_account_information,
    "20" => :merchant_account_information,
    "21" => :merchant_account_information,
    "22" => :merchant_account_information,
    "23" => :merchant_account_information,
    "24" => :merchant_account_information,
    "25" => :merchant_account_information,
    "26" => :merchant_account_information,
    "27" => :merchant_account_information,
    "28" => :merchant_account_information,
    "29" => :merchant_account_information,
    "30" => :merchant_account_information,
    "31" => :merchant_account_information,
    "32" => :merchant_account_information,
    "33" => :merchant_account_information,
    "34" => :merchant_account_information,
    "35" => :merchant_account_information,
    "36" => :merchant_account_information,
    "37" => :merchant_account_information,
    "38" => :merchant_account_information,
    "39" => :merchant_account_information,
    "40" => :merchant_account_information,
    "41" => :merchant_account_information,
    "42" => :merchant_account_information,
    "43" => :merchant_account_information,
    "44" => :merchant_account_information,
    "45" => :merchant_account_information,
    "46" => :merchant_account_information,
    "47" => :merchant_account_information,
    "48" => :merchant_account_information,
    "49" => :merchant_account_information,
    "50" => :merchant_account_information,
    "51" => :merchant_account_information,
    "52" => :merchant_category_code,
    "53" => :transaction_currency,
    "54" => :transaction_amount,
    "55" => :tip_or_convenience_indicator,
    "56" => :value_of_convenience_fee_fixed,
    "57" => :value_of_convenience_fee_percentage,
    "58" => :country_code,
    "59" => :merchant_name,
    "60" => :merchant_city,
    "61" => :postal_code,
    "62" => :additional_data_field_template,
    "63" => :crc,
    "64" => :merchant_information_language_template,
    "65" => :rfu_for_emvco,
    "66" => :rfu_for_emvco,
    "67" => :rfu_for_emvco,
    "68" => :rfu_for_emvco,
    "69" => :rfu_for_emvco,
    "70" => :rfu_for_emvco,
    "71" => :rfu_for_emvco,
    "72" => :rfu_for_emvco,
    "73" => :rfu_for_emvco,
    "74" => :rfu_for_emvco,
    "75" => :rfu_for_emvco,
    "76" => :rfu_for_emvco,
    "77" => :rfu_for_emvco,
    "78" => :rfu_for_emvco,
    "79" => :rfu_for_emvco,
    "80" => :unreserved_template,
    "81" => :unreserved_template,
    "82" => :unreserved_template,
    "83" => :unreserved_template,
    "84" => :unreserved_template,
    "85" => :unreserved_template,
    "86" => :unreserved_template,
    "87" => :unreserved_template,
    "88" => :unreserved_template,
    "89" => :unreserved_template,
    "90" => :unreserved_template,
    "91" => :unreserved_template,
    "92" => :unreserved_template,
    "93" => :unreserved_template,
    "94" => :unreserved_template,
    "95" => :unreserved_template,
    "96" => :unreserved_template,
    "97" => :unreserved_template,
    "98" => :unreserved_template,
    "99" => :unreserved_template
  }

  @root_specs %{
    payload_format_indicator:               %{must: true,  min_len: 2, max_len:  2, regex: ~r/(^01$)/,               parent: nil,                           is_template: false},
    point_of_initiation_method:             %{must: false, min_len: 2, max_len:  2, regex: ~r/(^11$)|(^12$)/,        parent: nil,                           is_template: false},
    merchant_account_information:           %{must: true,  min_len: 1, max_len: 99, regex: nil,                      parent: nil,                           is_template: false},
    merchant_category_code:                 %{must: true,  min_len: 4, max_len:  4, regex: ~r/^\d+$/,                parent: nil,                           is_template: false},
    transaction_currency:                   %{must: true,  min_len: 3, max_len:  3, regex: ~r/^\d+$/,                parent: nil,                           is_template: false},
    transaction_amount:                     %{must: false, min_len: 1, max_len: 13, regex: ~r/(^\d+\.\d+$)|(^\d+$)/, parent: nil,                           is_template: false},
    tip_or_convenience_indicator:           %{must: false, min_len: 2, max_len:  2, regex: ~r/^\d+$/,                parent: nil,                           is_template: false},
    value_of_convenience_fee_fixed:         %{must: false, min_len: 1, max_len: 13, regex: ~r/(^\d+\.\d+$)|(^\d+$)/, parent: :tip_or_convenience_indicator, is_template: false},
    value_of_convenience_fee_percentage:    %{must: false, min_len: 1, max_len:  5, regex: ~r/(^\d+\.\d+$)|(^\d+$)/, parent: :tip_or_convenience_indicator, is_template: false},
    country_code:                           %{must: true,  min_len: 2, max_len:  2, regex: ~r/^[a-zA-Z]{2}$/,        parent: nil,                           is_template: false},
    merchant_name:                          %{must: true,  min_len: 1, max_len: 25, regex: nil,                      parent: nil,                           is_template: false},
    merchant_city:                          %{must: true,  min_len: 1, max_len: 15, regex: nil,                      parent: nil,                           is_template: false},
    postal_code:                            %{must: false, min_len: 1, max_len: 10, regex: nil,                      parent: nil,                           is_template: false},
    additional_data_field_template:         %{must: false, min_len: 1, max_len: 99, regex: nil,                      parent: nil,                           is_template: true },
    crc:                                    %{must: true , min_len: 1, max_len:  4, regex: nil,                      parent: nil,                           is_template: false},
    merchant_information_language_template: %{must: false, min_len: 1, max_len: 99, regex: nil,                      parent: nil,                           is_template: false},
    rfu_for_emvco:                          %{must: false, min_len: 1, max_len: 99, regex: nil,                      parent: nil,                           is_template: false},
    unreserved_template:                    %{must: false, min_len: 1, max_len: 99, regex: nil,                      parent: nil,                           is_template: false}
  }

  @id_62_atoms %{
    "01" => :bill_number,
    "02" => :mobile_number,
    "03" => :store_label,
    "04" => :loyalty_number,
    "05" => :reference_label,
    "06" => :customer_label,
    "07" => :terminal_label,
    "08" => :purpose_of_transaction,
    "09" => :additional_consumer_data_request,
    "10" => :rfu_for_emvco,
    "11" => :rfu_for_emvco,
    "12" => :rfu_for_emvco,
    "13" => :rfu_for_emvco,
    "14" => :rfu_for_emvco,
    "15" => :rfu_for_emvco,
    "16" => :rfu_for_emvco,
    "17" => :rfu_for_emvco,
    "18" => :rfu_for_emvco,
    "19" => :rfu_for_emvco,
    "20" => :rfu_for_emvco,
    "21" => :rfu_for_emvco,
    "22" => :rfu_for_emvco,
    "23" => :rfu_for_emvco,
    "24" => :rfu_for_emvco,
    "25" => :rfu_for_emvco,
    "26" => :rfu_for_emvco,
    "27" => :rfu_for_emvco,
    "28" => :rfu_for_emvco,
    "29" => :rfu_for_emvco,
    "30" => :rfu_for_emvco,
    "31" => :rfu_for_emvco,
    "32" => :rfu_for_emvco,
    "33" => :rfu_for_emvco,
    "34" => :rfu_for_emvco,
    "35" => :rfu_for_emvco,
    "36" => :rfu_for_emvco,
    "37" => :rfu_for_emvco,
    "38" => :rfu_for_emvco,
    "39" => :rfu_for_emvco,
    "40" => :rfu_for_emvco,
    "41" => :rfu_for_emvco,
    "42" => :rfu_for_emvco,
    "43" => :rfu_for_emvco,
    "44" => :rfu_for_emvco,
    "45" => :rfu_for_emvco,
    "46" => :rfu_for_emvco,
    "47" => :rfu_for_emvco,
    "48" => :rfu_for_emvco,
    "49" => :rfu_for_emvco,
    "50" => :payment_system_specific_template,
    "51" => :payment_system_specific_template,
    "52" => :payment_system_specific_template,
    "53" => :payment_system_specific_template,
    "54" => :payment_system_specific_template,
    "55" => :payment_system_specific_template,
    "56" => :payment_system_specific_template,
    "57" => :payment_system_specific_template,
    "58" => :payment_system_specific_template,
    "59" => :payment_system_specific_template,
    "60" => :payment_system_specific_template,
    "61" => :payment_system_specific_template,
    "62" => :payment_system_specific_template,
    "63" => :payment_system_specific_template,
    "64" => :payment_system_specific_template,
    "65" => :payment_system_specific_template,
    "66" => :payment_system_specific_template,
    "67" => :payment_system_specific_template,
    "68" => :payment_system_specific_template,
    "69" => :payment_system_specific_template,
    "70" => :payment_system_specific_template,
    "71" => :payment_system_specific_template,
    "72" => :payment_system_specific_template,
    "73" => :payment_system_specific_template,
    "74" => :payment_system_specific_template,
    "75" => :payment_system_specific_template,
    "76" => :payment_system_specific_template,
    "77" => :payment_system_specific_template,
    "78" => :payment_system_specific_template,
    "79" => :payment_system_specific_template,
    "80" => :payment_system_specific_template,
    "81" => :payment_system_specific_template,
    "82" => :payment_system_specific_template,
    "83" => :payment_system_specific_template,
    "84" => :payment_system_specific_template,
    "85" => :payment_system_specific_template,
    "86" => :payment_system_specific_template,
    "87" => :payment_system_specific_template,
    "88" => :payment_system_specific_template,
    "89" => :payment_system_specific_template,
    "90" => :payment_system_specific_template,
    "91" => :payment_system_specific_template,
    "92" => :payment_system_specific_template,
    "93" => :payment_system_specific_template,
    "94" => :payment_system_specific_template,
    "95" => :payment_system_specific_template,
    "96" => :payment_system_specific_template,
    "97" => :payment_system_specific_template,
    "98" => :payment_system_specific_template,
    "99" => :payment_system_specific_template
  }

  @id_62_specs [

  ]

  def root_id_atoms() do
    @root_id_atoms
  end

  def root_code(id_atom) do
    root_id_atoms()
    |> Enum.find(fn {_, v} -> v == id_atom end)
    |> elem(0)
  end

  def root_specs() do
    @root_specs
  end
end
