defmodule Exemvi.MPM.DataObject do

  @code_atoms %{
    "00" => :payload_format_indicator,
    "01" => :point_of_initiation_method,
    "02" => :merchant_account_information,
    "03" => :merchant_account_information,
    "04" => :merchant_account_information,
    "05" => :merchant_account_information,
    "06" => :merchant_account_information,
    "07" => :merchant_account_information,
    "08" => :merchant_account_information,
    "09" => :merchant_account_information,
    "10" => :merchant_account_information,
    "11" => :merchant_account_information,
    "12" => :merchant_account_information,
    "13" => :merchant_account_information,
    "14" => :merchant_account_information,
    "15" => :merchant_account_information,
    "16" => :merchant_account_information,
    "17" => :merchant_account_information,
    "18" => :merchant_account_information,
    "19" => :merchant_account_information,
    "20" => :merchant_account_information,
    "21" => :merchant_account_information,
    "22" => :merchant_account_information,
    "23" => :merchant_account_information,
    "24" => :merchant_account_information,
    "25" => :merchant_account_information,
    "26" => :merchant_account_information,
    "27" => :merchant_account_information,
    "28" => :merchant_account_information,
    "29" => :merchant_account_information,
    "30" => :merchant_account_information,
    "31" => :merchant_account_information,
    "32" => :merchant_account_information,
    "33" => :merchant_account_information,
    "34" => :merchant_account_information,
    "35" => :merchant_account_information,
    "36" => :merchant_account_information,
    "37" => :merchant_account_information,
    "38" => :merchant_account_information,
    "39" => :merchant_account_information,
    "40" => :merchant_account_information,
    "41" => :merchant_account_information,
    "42" => :merchant_account_information,
    "43" => :merchant_account_information,
    "44" => :merchant_account_information,
    "45" => :merchant_account_information,
    "46" => :merchant_account_information,
    "47" => :merchant_account_information,
    "48" => :merchant_account_information,
    "49" => :merchant_account_information,
    "50" => :merchant_account_information,
    "51" => :merchant_account_information,
    "52" => :merchant_category_code,
    "53" => :transaction_currency,
    "54" => :transaction_amount,
    "55" => :tip_or_convenience_indicator,
    "56" => :value_of_convenience_fee_fixed,
    "57" => :value_of_convenience_fee_percentage,
    "58" => :country_code,
    "59" => :merchant_name,
    "60" => :merchant_city,
    "61" => :postal_code,
    "62" => :additional_data_field_template,
    "63" => :crc,
    "64" => :merchant_information_language_template,
    "65" => :rfu_for_emvco,
    "66" => :rfu_for_emvco,
    "67" => :rfu_for_emvco,
    "68" => :rfu_for_emvco,
    "69" => :rfu_for_emvco,
    "70" => :rfu_for_emvco,
    "71" => :rfu_for_emvco,
    "72" => :rfu_for_emvco,
    "73" => :rfu_for_emvco,
    "74" => :rfu_for_emvco,
    "75" => :rfu_for_emvco,
    "76" => :rfu_for_emvco,
    "77" => :rfu_for_emvco,
    "78" => :rfu_for_emvco,
    "79" => :rfu_for_emvco,
    "80" => :unreserved_template,
    "81" => :unreserved_template,
    "82" => :unreserved_template,
    "83" => :unreserved_template,
    "84" => :unreserved_template,
    "85" => :unreserved_template,
    "86" => :unreserved_template,
    "87" => :unreserved_template,
    "88" => :unreserved_template,
    "89" => :unreserved_template,
    "90" => :unreserved_template,
    "91" => :unreserved_template,
    "92" => :unreserved_template,
    "93" => :unreserved_template,
    "94" => :unreserved_template,
    "95" => :unreserved_template,
    "96" => :unreserved_template,
    "97" => :unreserved_template,
    "98" => :unreserved_template,
    "99" => :unreserved_template
  }

  @specifications [
    %{atom: :payload_format_indicator,                maxlen:  2, format: :num, mandatory: true },
    %{atom: :point_of_initiation_method,              maxlen:  2, format: :num, mandatory: false},
    %{atom: :merchant_account_information,            maxlen: 99, format: :ans, mandatory: true },
    %{atom: :merchant_category_code,                  maxlen:  4, format: :num, mandatory: true },
    %{atom: :transaction_currency,                    maxlen:  3, format: :num, mandatory: true },
    %{atom: :transaction_amount,                      maxlen: 13, format: :ans, mandatory: false},
    %{atom: :tip_or_convenience_indicator,            maxlen:  2, format: :num, mandatory: false},
    %{atom: :value_of_convenience_fee_fixed,          maxlen: 13, format: :ans, mandatory: false},
    %{atom: :value_of_convenience_fee_percentage,     maxlen:  5, format: :ans, mandatory: false},
    %{atom: :country_code,                            maxlen:  2, format: :ans, mandatory: true },
    %{atom: :merchant_name,                           maxlen: 25, format: :ans, mandatory: true },
    %{atom: :merchant_city,                           maxlen: 15, format: :ans, mandatory: true },
    %{atom: :postal_code,                             maxlen: 10, format: :ans, mandatory: false},
    %{atom: :additional_data_field_template,          maxlen: 99, format: :str, mandatory: false},
    %{atom: :crc,                                     maxlen:  4, format: :ans, mandatory: true },
    %{atom: :merchant_information_language_template,  maxlen: 99, format: :str, mandatory: false},
    %{atom: :rfu_for_emvco,                           maxlen: 99, format: :str, mandatory: false},
    %{atom: :unreserved_template,                     maxlen: 99, format: :str, mandatory: false}
  ]

  def code_atoms() do
    @code_atoms
  end

  def specifications() do
    @specifications
  end
end
