defmodule Exemvi.MPM.DataObject do

  @code_atoms %{
    "00" => :payload_format_indicator,
    "01" => :point_of_initiation_method,
    "02" => :merchant_account_information,
    "03" => :merchant_account_information,
    "04" => :merchant_account_information,
    "05" => :merchant_account_information,
    "06" => :merchant_account_information,
    "07" => :merchant_account_information,
    "08" => :merchant_account_information,
    "09" => :merchant_account_information,
    "10" => :merchant_account_information,
    "11" => :merchant_account_information,
    "12" => :merchant_account_information,
    "13" => :merchant_account_information,
    "14" => :merchant_account_information,
    "15" => :merchant_account_information,
    "16" => :merchant_account_information,
    "17" => :merchant_account_information,
    "18" => :merchant_account_information,
    "19" => :merchant_account_information,
    "20" => :merchant_account_information,
    "21" => :merchant_account_information,
    "22" => :merchant_account_information,
    "23" => :merchant_account_information,
    "24" => :merchant_account_information,
    "25" => :merchant_account_information,
    "26" => :merchant_account_information,
    "27" => :merchant_account_information,
    "28" => :merchant_account_information,
    "29" => :merchant_account_information,
    "30" => :merchant_account_information,
    "31" => :merchant_account_information,
    "32" => :merchant_account_information,
    "33" => :merchant_account_information,
    "34" => :merchant_account_information,
    "35" => :merchant_account_information,
    "36" => :merchant_account_information,
    "37" => :merchant_account_information,
    "38" => :merchant_account_information,
    "39" => :merchant_account_information,
    "40" => :merchant_account_information,
    "41" => :merchant_account_information,
    "42" => :merchant_account_information,
    "43" => :merchant_account_information,
    "44" => :merchant_account_information,
    "45" => :merchant_account_information,
    "46" => :merchant_account_information,
    "47" => :merchant_account_information,
    "48" => :merchant_account_information,
    "49" => :merchant_account_information,
    "50" => :merchant_account_information,
    "51" => :merchant_account_information,
    "52" => :merchant_category_code,
    "53" => :transaction_currency,
    "54" => :transaction_amount,
    "55" => :tip_or_convenience_indicator,
    "56" => :value_of_convenience_fee_fixed,
    "57" => :value_of_convenience_fee_percentage,
    "58" => :country_code,
    "59" => :merchant_name,
    "60" => :merchant_city,
    "61" => :postal_code,
    "62" => :additional_data_field_template,
    "63" => :crc,
    "64" => :merchant_information_language_template,
    "65" => :rfu_for_emvco,
    "66" => :rfu_for_emvco,
    "67" => :rfu_for_emvco,
    "68" => :rfu_for_emvco,
    "69" => :rfu_for_emvco,
    "70" => :rfu_for_emvco,
    "71" => :rfu_for_emvco,
    "72" => :rfu_for_emvco,
    "73" => :rfu_for_emvco,
    "74" => :rfu_for_emvco,
    "75" => :rfu_for_emvco,
    "76" => :rfu_for_emvco,
    "77" => :rfu_for_emvco,
    "78" => :rfu_for_emvco,
    "79" => :rfu_for_emvco,
    "80" => :unreserved_template,
    "81" => :unreserved_template,
    "82" => :unreserved_template,
    "83" => :unreserved_template,
    "84" => :unreserved_template,
    "85" => :unreserved_template,
    "86" => :unreserved_template,
    "87" => :unreserved_template,
    "88" => :unreserved_template,
    "89" => :unreserved_template,
    "90" => :unreserved_template,
    "91" => :unreserved_template,
    "92" => :unreserved_template,
    "93" => :unreserved_template,
    "94" => :unreserved_template,
    "95" => :unreserved_template,
    "96" => :unreserved_template,
    "97" => :unreserved_template,
    "98" => :unreserved_template,
    "99" => :unreserved_template
  }

  @specifications [
    %{atom: :payload_format_indicator,               must:  true, min_len: 2, max_len:  2, regex: ~r/(01)/},
    %{atom: :point_of_initiation_method,             must: false, min_len: 2, max_len:  2, regex: ~r/(11)|(12)/},
    %{atom: :merchant_account_information,           must:  true, min_len: 1, max_len: 99, regex: nil},
    %{atom: :merchant_category_code,                 must:  true, min_len: 4, max_len:  4, regex: ~r/\d+/},
    %{atom: :transaction_currency,                   must:  true, min_len: 3, max_len:  3, regex: ~r/\d+/},
    %{atom: :transaction_amount,                     must: false, min_len: 1, max_len: 13, regex: ~r/(\d+\.\d+)|(^\d+$)/},
    %{atom: :tip_or_convenience_indicator,           must: false, min_len: 2, max_len:  2, regex: ~r/\d+/},
    %{atom: :value_of_convenience_fee_fixed,         must: false, min_len: 1, max_len: 13, regex: ~r/(\d+\.\d+)|(^\d+$)/},
    %{atom: :value_of_convenience_fee_percentage,    must: false, min_len: 1, max_len:  5, regex: ~r/(\d+\.\d+)|(^\d+$)/},
    %{atom: :country_code,                           must:  true, min_len: 2, max_len:  2, regex: ~r/[a-zA-Z]{2}/},
    %{atom: :merchant_name,                          must:  true, min_len: 1, max_len: 25, regex: nil},
    %{atom: :merchant_city,                          must:  true, min_len: 1, max_len: 15, regex: nil},
    %{atom: :postal_code,                            must: false, min_len: 1, max_len: 10, regex: nil},
    %{atom: :additional_data_field_template,         must: false, min_len: 1, max_len: 99, regex: nil},
    %{atom: :crc,                                    must:  true, min_len: 1, max_len:  4, regex: nil},
    %{atom: :merchant_information_language_template, must: false, min_len: 1, max_len: 99, regex: nil},
    %{atom: :rfu_for_emvco,                          must: false, min_len: 1, max_len: 99, regex: nil},
    %{atom: :unreserved_template,                    must: false, min_len: 1, max_len: 99, regex: nil}
  ]

  def code_atoms() do
    @code_atoms
  end

  def specifications() do
    @specifications
  end
end
