name: Elixir CI

on:
  push:
    branches:
      - '*'
    pull_request:
      branches:
      - master

jobs:
  build:

    name: Test (${{matrix.elixir}}/${{matrix.otp}})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp: [25.x, 26.x, 27.x, 28.x]
        elixir: [1.15.x, 1.16.x, 1.17.x, 1.18.x]
        exclude:
          - otp: 27.x
            elixir: 1.15.x
          - otp: 27.x
            elixir: 1.16.x
          - otp: 28.x
            elixir: 1.15.x
          - otp: 28.x
            elixir: 1.16.x            
          - otp: 28.x
            elixir: 1.17.x            

    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{matrix.otp}}-${{matrix.elixir}}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{matrix.otp}}-${{matrix.elixir}}-
      - name: Install dependencies
        run: mix deps.get
      - name: Run tests
        run: mix test
