name: Publish to Hex

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Publish to Hex.pm
        uses: hipcall/github_action_publish_hex@v1
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}